# Generated by Django 3.0.1 on 2019-12-31 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapps', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('status', models.PositiveSmallIntegerField()),
                ('updated_by', models.PositiveSmallIntegerField()),
                ('date_signed', models.DateTimeField(default=datetime.datetime.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
